# Default values for nginx-app

replicaCount: 1
image:
  repository: nginx
  tag: staging-v2.15.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
